// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc45-RR4wnzo4qML5TllGpIAQJgBP7ols',
    appId: '1:788623339396:web:b091908567e6b59d2677d1',
    messagingSenderId: '788623339396',
    projectId: 'fspu-6a163',
    authDomain: 'fspu-6a163.firebaseapp.com',
    storageBucket: 'fspu-6a163.firebasestorage.app',
    measurementId: 'G-NVYRX1QRL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_q-zSG5E4weoSdXejee5xDZi4HKv13k',
    appId: '1:788623339396:android:e26121c0dcc0d8d12677d1',
    messagingSenderId: '788623339396',
    projectId: 'fspu-6a163',
    storageBucket: 'fspu-6a163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUMH7CeDixTAF9K3X9rwK2MrB73wdVd4',
    appId: '1:788623339396:ios:671a0f1e9807c9912677d1',
    messagingSenderId: '788623339396',
    projectId: 'fspu-6a163',
    storageBucket: 'fspu-6a163.firebasestorage.app',
    iosBundleId: 'com.example.fspu',
  );
}
